#!/bin/zsh

DATE_FORMAT="%a %b %_d %_I:%M %p"
DZEN_ICONPATH=/home/jon/etc/dzen/icons

fdate() {
    date +$DATE_FORMAT
}

while true; do
    PDATE=$(fdate)

    PSONG=""
    if [ "`mpc | wc -l`" = "3" ] ; then
        if [ "`mpc | sed -n 's/\[\([a-z]*\).*/\1/p'`" = "playing" ] ; then
            PSONG=$PSONG"^i(${DZEN_ICONPATH}/play.xbm) "
	else
	    PSONG=$PSONG"^i(${DZEN_ICONPATH}/pause.xbm) "
	fi
        PSONG=$PSONG`mpc | sed -n '1p'`
    else
	PSONG=$PSONG"^i(${DZEN_ICONPATH}/note.xbm) No Music"
    fi

    print "${PSONG} ^i(${DZEN_ICONPATH}/clock.xbm) ${PDATE} "

    sleep 1
done
