if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr &

# tail -f ~/.dmplex/pipe | ~/bin/dmplex | ~/bin/dzen2 -ta l -xs 1 -h 24 -e '' & 
# /home/jon/bin/sysclock &
# urxvtd -q -o -f
nitrogen --restore &
# exec ck-launch-session startxfce4
exec xmonad
