if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr &
xset s off
xset -dpms
urxvtd -q -o -f
sh ~/.fehbg &
exec i3
