if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr &

tail -f ~/.dzen/pipe | dmplex | dzen2 -ta l -xs 1 -h 24 -e '' & 
/home/jon/bin/sysbar &
urxvtd -q -o -f
sh ~/.fehbg &
exec xmonad
