fpath=($HOME/.zsh/functions/Prompts $fpath)

# Completion
autoload -Uz compinit
compinit

# Options
setopt autocd extendedglob

# Emacs keybindings
bindkey -e

# Prompt
autoload -Uz promptinit; promptinit
prompt eyolfson blue cyan

# Better TAB Completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion::complete:*' use-cache 1

# LS Colours
eval `dircolors`

# Variables
export PATH="${HOME}/bin:${PATH}"
#export PATH="${PATH}:${HOME}/opt/pin"

#export GERONIMO_HOME=$HOME/workspace/geronimo-jetty7-minimal-2.2
#export CLASSPATH=$HOME/lib/java/antlr-3.2.jar
#export CLASSPATH=$CLASSPATH:$HOME/workspace/ece251-a2-solns/classes

#export GROFF_NO_SGR=
#export LESS_TERMCAP_mb=$'\E[01;31m'    # Begin Blinking
#export LESS_TERMCAP_md=$'\E[01;31m'    # Begin Bold
#export LESS_TERMCAP_me=$'\E[0m'        # End Mode
#export LESS_TERMCAP_se=$'\E[0m'        # End Standout-Mode
#export LESS_TERMCAP_so=$'\E[01;47;34m' # Begin Standout-Mode
#export LESS_TERMCAP_ue=$'\E[0m'        # End Underline
#export LESS_TERMCAP_us=$'\E[01;32m'    # Begin Underline

# History
HISTFILE=~/.zhistory
HISTSIZE=1000
SAVEHIST=1000

# Aliases
alias ls='ls --color=auto'
alias grep='grep --colour=auto'
alias git-first-push='git push origin master:refs/heads/master'

# Backup command
backup() {
    sudo tar cvf /home/backup.tar -C / \
        etc/conf.d/git-daemon.conf \
        etc/group \
        etc/httpd/conf/httpd.conf \
        etc/httpd/conf/extra/httpd-default.conf \
        etc/httpd/conf/extra/httpd-vhosts.conf \
        etc/makepkg.conf \
        etc/murmur.ini \
        etc/nginx/conf/nginx.conf \
        etc/ntp.conf \
        etc/pacman.conf \
        etc/pacman.d/mirrorlist \
        etc/passwd \
        etc/rc.conf \
        etc/resolv.conf \
        srv/gitosis \
        srv/http \
        usr/share/slim/themes/archlinux-simplyblack/slim.theme \
        var/lib/postgres
    sudo chmod 600 /home/backup.tar
}
